BEGIN;

CREATE TABLE startup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cnpj VARCHAR(14) UNIQUE
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    senha_hash TEXT NOT NULL
);

CREATE TABLE startup_usuario (
    startup_id BIGINT NOT NULL REFERENCES startup(id),
    usuario_id BIGINT NOT NULL REFERENCES usuario(id),
    PRIMARY KEY (startup_id, usuario_id)
);

CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE documento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    startup_id BIGINT NOT NULL REFERENCES startup(id),
    categoria_id BIGINT NOT NULL REFERENCES categoria(id),
    responsavel_id BIGINT NOT NULL,
    nome VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pendente',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (startup_id, responsavel_id)
        REFERENCES startup_usuario(startup_id, usuario_id),
    CHECK (status IN ('Pendente', 'Em análise', 'Aprovado'))
);

CREATE TABLE documento_versao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES documento(id),
    numero_versao INTEGER NOT NULL CHECK (numero_versao > 0),
    nome_arquivo VARCHAR(255) NOT NULL,
    localizacao_arquivo TEXT NOT NULL,
    enviado_por BIGINT NOT NULL REFERENCES usuario(id),
    enviado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (documento_id, numero_versao)
);

CREATE TABLE comentario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES documento(id),
    autor_id BIGINT NOT NULL REFERENCES usuario(id),
    conteudo TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE historico_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES documento(id),
    status_anterior VARCHAR(20),
    status_novo VARCHAR(20) NOT NULL,
    alterado_por BIGINT NOT NULL REFERENCES usuario(id),
    alterado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (status_anterior IN ('Pendente', 'Em análise', 'Aprovado')),
    CHECK (status_novo IN ('Pendente', 'Em análise', 'Aprovado')),
    CHECK (status_anterior IS DISTINCT FROM status_novo)
);

COMMIT;
